layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  - facebook: adityaasahoo
  - hackerrank: adityaarpansahoo
  - instagram: adityaa_sahoo
  # keybase: your_username
  - linkedin: arpan-aditya
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  - telegram: arpan_aditya
  - twitter: adityaa_sahoo
  # unsplash: your_username
  # vk: your_username
  - website: http://linktr.ee/arpanaditya
  # youtube: your_username

topics:
  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/html/html.png

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
    
  - name: Sass
    web_url: https://github.com/topics/JavaScript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png
